name: covid-19-community 

channels:
  - conda-forge
  - anaconda
  - esri

dependencies:
  - python=3.7
  - openjdk=11.0.1
  - jupyterlab=2.1.5
  - pandas
  - xlrd
  - matplotlib
  - seaborn=0.11.0
  - biopython
  - papermill=2.1.0
  - nodejs>=10.0.0
  - ipywidgets=7.5.1
  - scikit-learn=0.23.2
  - arcgis=1.8.1
  - geocoder
  - unidecode
  - python-Levenshtein
  - pycountry
  - geopy
  - pip
  - pip:
    - rcsbsearch==0.2.1
    - --pre
    - py2neo
