name: covid-19-community 

channels:
  - conda-forge
  - anaconda
  - esri

dependencies:
  - python>=3.8
  - openjdk=11.0.1
  - jupyterlab=2.1.1
  - pandas
  - xlrd
  - matplotlib
  - biopython
  - py2neo
  - papermill=2.1.0
  - widgetsnbextension
  - ipywidgets
  - arcgis=1.8.1
  - pip
  - pip:
    - rcsbsearch==0.2.1
