name: covid-19-community 

channels:
  - anaconda
  - conda-forge

dependencies:
  - python>=3.7
  - jupyter
  - jupyterlab
  - openjdk=11.0.1
  - pandas
  - matplotlib
  - plotly
  - biopython
  - py2neo
