name: covid-19-community 

channels:
  - conda-forge
  - anaconda

dependencies:
  - python>=3.8
  - jupyterlab=2.1.1
  - pandas
  - xlrd
  - matplotlib
  - biopython
  - py2neo
  - papermill=2.1.0
  - widgetsnbextension
  - ipywidgets
