name: covid-19-community 

channels:
  - conda-forge
  - anaconda
  - esri
  - bioconda

dependencies:
  - python=3.7
  - openjdk=11.0.1
  - jupyterlab
  - pandas
  - dask
  - aiohttp
  - requests
  - xlrd
  - matplotlib
  - seaborn=0.11.0
  - biopython
  - papermill=2.1.0
  - nodejs>=10.0.0
  - ipywidgets=7.6.2
  - scikit-learn=0.23.2
  - arcgis=1.8.1
  - bcbio-gff=0.6.6
  - geocoder
  - py3Dmol=0.8.0
  - unidecode
  - python-Levenshtein
  - pycountry
  - geopy
  - ipycytoscape
  - pip
  - pip:
    - --pre
    - py2neo
